---
############################
# Build_Packages_and_tools #
############################
- name: Set package manager var
  set_fact:
    package_var: "latest"

- name: Install Build Tool Packages
  package: "name={{ item }} state={{ package_var }}"
  with_items: "{{ Build_Tool_Packages }}"
  tags: build_tools
