---
#####################
# gmake from source #
#####################

# Conditions:
# Check if make is installed in /usr/local/bin/make on CentOS/RHEL on ppc64le,
# s390x, x86_64, on SLES12 on x86_64 and on Ubuntu14 on x86_64
# Proceed with downloading and installing make
# Addresses https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/499

- name: Test if self-built make 4.1 is available
  shell: /usr/local/bin/make --version >/dev/null
  ignore_errors: yes
  register: goodmake_installed
  when:
    - (ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or (((ansible_distribution == "SLES" and ansible_distribution_major_version == "12") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")) and ansible_architecture == "x86_64"))
  tags: goodmake_source

- name: Download make 4.1 source
  get_url:
    url: https://ftp.gnu.org/gnu/make/make-4.1.tar.gz
    dest: /tmp/make-4.1.tar.gz
    mode: 0440
  when:
    - (ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or (((ansible_distribution == "SLES" and ansible_distribution_major_version == "12") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")) and ansible_architecture == "x86_64"))
    - goodmake_installed.rc != 0
  tags: goodmake_source

- name: Extract make 4.1 source
  unarchive:
    src: /tmp/make-4.1.tar.gz
    dest: /tmp
    copy: False
  when:
    - (ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or (((ansible_distribution == "SLES" and ansible_distribution_major_version == "12") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")) and ansible_architecture == "x86_64"))
    - goodmake_installed.rc != 0
  tags: goodmake_source

- name: Set numOfCPUs on {{ ansible_distribution }} {{ ansible_distribution_major_version}} {{ ansible_architecture }}
  set_fact:
    numOfCPUs: {{ ansible_processor_cores }}
  when:
    - ansible_architecture == "s390x"
    - goodmake_installed.rc != 0
  tags: goodmake_source

- name: Set numOfCPUs on {{ ansible_distribution }} {{ ansible_distribution_major_version}} {{ ansible_architecture }}
  set_fact:
    numOfCPUs: {{ ansible_processor_vcpus }}
  when:
    - ansible_architecture != "s390x"
    - goodmake_installed.rc != 0
  tags: goodmake_source

- name: Compile and install make 4.1 from source
  shell: cd /tmp/make-4.1 && ./configure --prefix=/usr/local && make clean && make -j {{ numOfCPUs }} && make install
  when:
    - (ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or (((ansible_distribution == "SLES" and ansible_distribution_major_version == "12") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")) and ansible_architecture == "x86_64"))
    - goodmake_installed.rc != 0
  tags: goodmake_source

- name: Create symlink for /usr/bin/gmake to our built 4.1 in /usr/local/bin/make
  file:
    src: /usr/local/bin/make
    dest: /usr/local/bin/gmake
    owner: root
    group: root
    state: link
  when:
    - (ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or (((ansible_distribution == "SLES" and ansible_distribution_major_version == "12") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")) and ansible_architecture == "x86_64"))
    - goodmake_installed.rc != 0
  tags: goodmake_source
